void html_start(const char *, const char *);
void html_end(void);
void html_head_start(void);
void html_head_end(void);
void html_meta(const char *, const char *, const char *);
void html_title(const char *, ...);
void html_style_start(const char *);
void html_style_end(void);
void html_text_css(const char *, const char *, ...);
void html_body_start(void);
void html_body_end(void);
void html_div_start(const char *);
void html_div_end(void);
void html_h1_start(const char *);
void html_h1_end(void);
void html_a_start(const char *, const char *);
void html_a_end(void);
void html_a(const char *, const char *, const char *, ...);
void html_table_start(const char *);
void html_table_end(void);
void html_caption_start(const char *);
void html_caption_end(void);
void html_caption(const char *, const char *, ...);
void html_tr_start(const char *);
void html_tr_end(void);
void html_td_start(const char *, unsigned);
void html_td_end(void);
